country: China
province: Shandong
city: Taian

subject:
  - java
  - python
  - html

enterprise:
  name: zhangsan
  age: 12
  subject:
    - java
    - python
    - html

subject2: [java,python,html]

users:
  - name: zhangsan
    age: 12
  - name: lisi
    age: 14


users2:
  -
    name: zhangsan
    age: 12
  -
    name: lisi
    age: 14

users3: [{name: zhangsan, age: 12},{name: lisi, age: 14}]

server:
  port: 80


datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ssm_db
  username: root
  password: 123456


baseDir: /usr/local/file

center:
  dataDir: ${baseDir}/data
  tmpDir: ${baseDir}/tmp
  logDir: ${baseDir}/log